apiVersion: v1
data:
  POSTGRES_DATABASE: postgres
  POSTGRES_PASSWORD: didwjdgns1
  POSTGRES_USERNAME: postgres
kind: ConfigMap
metadata:
  # creationTimestamp: null
  labels:
    io.kompose.service: auth-postgres-db-auth-docker-env
  name: db-auth-docker-env
